#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Wed May  1 13:55:55 2013

import wx, os, pwd

# begin wxGlade: extracode
# end wxGlade


class FrameJuego(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FrameJuego.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.explicacion = wx.StaticText(self, -1, u"Ejecute el demonio, y empiece a probar\n números del 1 al 9, hasta adivinarlo.", style=wx.ALIGN_CENTRE)
        self.spin_ctrl_1 = wx.SpinCtrl(self, -1, "", min=0, max=9)
        self.button_1 = wx.Button(self, -1, u"¡Probar!")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FrameJuego.__set_properties
        self.SetTitle("Juego para sistemas operativos.")
        self.SetSize((621, 307))
        self.explicacion.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.button_1.SetFont(wx.Font(30, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade
        self.button_1.Bind(wx.EVT_BUTTON, self.boton_probar)

    def __do_layout(self):
        # begin wxGlade: FrameJuego.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.explicacion, 0, wx.ALL | wx.EXPAND, 0)
        sizer_2.Add(self.spin_ctrl_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.button_1, 2, wx.ALL | wx.EXPAND, 3)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade
    
    def boton_probar(self, event):
        '''
        Función que gestiona el evento al apretar el botón "Probar".
          Guarda el número escogido con el spinner en un archivo de texto en
          la carpeta del usuario que lo ejecuta.
        '''
        nombreUsuario = pwd.getpwuid(os.getuid())[0]
        f=open('/home/'+nombreUsuario+'/juego_SO',"w+")
        f.write(str(self.spin_ctrl_1.GetValue()))
        f.close()
        


# end of class FrameJuego
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = FrameJuego(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
